/**
 * Alaska career hubs (region US-AK under country US).
 * Scheduled commercial fields only. Anchorage is the Jet-A producer.
 * No road link to the lower 48.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';

export type UsAkCareerHubDef = {
  icao: string;
  name: string;
  region: 'US-AK';
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.05, supplies: 1.0, perishables: 0.95 },
  consume: { electronics: 0.8, machinery: 0.85, fuel: 0.9 },
} as const;

/** 57 scheduled Alaska hubs. PANC is the state gateway. */
export const US_AK_CAREER_HUBS: readonly UsAkCareerHubDef[] = [
  {
    icao: 'PABE',
    name: "Bethel",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 60.7798,
    lon: -161.838,
    ...drySpoke,
  },
  {
    icao: 'PABR',
    name: "Wiley Post Will Rogers Memorial",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 71.2854,
    lon: -156.766,
    ...drySpoke,
  },
  {
    icao: 'PACD',
    name: "Cold Bay",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 55.2079,
    lon: -162.725,
    ...drySpoke,
  },
  {
    icao: 'PACV',
    name: "Merle K (Mudhole) Smith",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 60.4918,
    lon: -145.478,
    ...drySpoke,
  },
  {
    icao: 'PADE',
    name: "Deering",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 66.0689,
    lon: -162.7669,
    ...drySpoke,
  },
  {
    icao: 'PADK',
    name: "Adak",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 51.8836,
    lon: -176.6428,
    ...drySpoke,
  },
  {
    icao: 'PADL',
    name: "Dillingham",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.0447,
    lon: -158.505,
    ...drySpoke,
  },
  {
    icao: 'PADQ',
    name: "Kodiak",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 57.75,
    lon: -152.494,
    ...drySpoke,
  },
  {
    icao: 'PADU',
    name: "Tom Madsen (Dutch Harbor)",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 53.8988,
    lon: -166.545,
    ...drySpoke,
  },
  {
    icao: 'PAEM',
    name: "Emmonak",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.7861,
    lon: -164.491,
    ...drySpoke,
  },
  {
    icao: 'PAEN',
    name: "Kenai Municipal",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 60.5709,
    lon: -151.2452,
    ...drySpoke,
  },
  {
    icao: 'PAFA',
    name: "Fairbanks International",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 64.8151,
    lon: -147.856,
    ...drySpoke,
  },
  {
    icao: 'PAFM',
    name: "Ambler",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 67.1055,
    lon: -157.8553,
    ...drySpoke,
  },
  {
    icao: 'PAGA',
    name: "Edward G. Pitka Sr",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 64.7362,
    lon: -156.937,
    ...drySpoke,
  },
  {
    icao: 'PAGK',
    name: "Gulkana",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.1559,
    lon: -145.4547,
    ...drySpoke,
  },
  {
    icao: 'PAGM',
    name: "Gambell",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 63.7677,
    lon: -171.7333,
    ...drySpoke,
  },
  {
    icao: 'PAGS',
    name: "Gustavus",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 58.4253,
    lon: -135.707,
    ...drySpoke,
  },
  {
    icao: 'PAHC',
    name: "Holy Cross",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.1883,
    lon: -159.775,
    ...drySpoke,
  },
  {
    icao: 'PAHL',
    name: "Huslia",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 65.6979,
    lon: -156.351,
    ...drySpoke,
  },
  {
    icao: 'PAHN',
    name: "Haines",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.2439,
    lon: -135.5239,
    ...drySpoke,
  },
  {
    icao: 'PAHO',
    name: "Homer",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.6445,
    lon: -151.4792,
    ...drySpoke,
  },
  {
    icao: 'PAII',
    name: "Egegik",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 58.1844,
    lon: -157.3749,
    ...drySpoke,
  },
  {
    icao: 'PAIK',
    name: "Bob Baker Memorial",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 66.9761,
    lon: -160.439,
    ...drySpoke,
  },
  {
    icao: 'PAIL',
    name: "Iliamna",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.7544,
    lon: -154.911,
    ...drySpoke,
  },
  {
    icao: 'PAJN',
    name: "Juneau International",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 58.3549,
    lon: -134.5744,
    ...drySpoke,
  },
  {
    icao: 'PAKN',
    name: "King Salmon",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 58.6778,
    lon: -156.652,
    ...drySpoke,
  },
  {
    icao: 'PAKP',
    name: "Anaktuvuk Pass",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 68.1336,
    lon: -151.743,
    ...drySpoke,
  },
  {
    icao: 'PAKT',
    name: "Ketchikan International",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 55.3556,
    lon: -131.714,
    ...drySpoke,
  },
  {
    icao: 'PAKW',
    name: "Klawock",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 55.5792,
    lon: -133.076,
    ...drySpoke,
  },
  {
    icao: 'PAMC',
    name: "McGrath",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.9529,
    lon: -155.606,
    ...drySpoke,
  },
  {
    icao: 'PAMR',
    name: "Merrill Field",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 61.2128,
    lon: -149.844,
    ...drySpoke,
  },
  {
    icao: 'PAMY',
    name: "Mekoryuk",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 60.3723,
    lon: -166.2698,
    ...drySpoke,
  },
  {
    icao: 'PANC',
    name: "Ted Stevens Anchorage International",
    region: 'US-AK',
    hubTier: 'major',
    lat: 61.179,
    lon: -149.9926,
    produce: { general: 1.35, supplies: 1.2, perishables: 1.1 },
    consume: { electronics: 1.05, machinery: 1.1, fuel: 1.2 },
  },
  {
    icao: 'PANI',
    name: "Aniak",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 61.5816,
    lon: -159.543,
    ...drySpoke,
  },
  {
    icao: 'PANV',
    name: "Anvik",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.6467,
    lon: -160.191,
    ...drySpoke,
  },
  {
    icao: 'PAOM',
    name: "Nome",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 64.5122,
    lon: -165.445,
    ...drySpoke,
  },
  {
    icao: 'PAOR',
    name: "Northway",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 62.9613,
    lon: -141.929,
    ...drySpoke,
  },
  {
    icao: 'PAOT',
    name: "Ralph Wien Memorial",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 66.8847,
    lon: -162.599,
    ...drySpoke,
  },
  {
    icao: 'PAPB',
    name: "St George",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 56.5773,
    lon: -169.6638,
    ...drySpoke,
  },
  {
    icao: 'PAPG',
    name: "Petersburg James A Johnson",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 56.8017,
    lon: -132.945,
    ...drySpoke,
  },
  {
    icao: 'PAPH',
    name: "Port Heiden",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 56.9579,
    lon: -158.6302,
    ...drySpoke,
  },
  {
    icao: 'PAPM',
    name: "Platinum",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.0177,
    lon: -161.8279,
    ...drySpoke,
  },
  {
    icao: 'PAQT',
    name: "Nuiqsut",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 70.21,
    lon: -151.006,
    ...drySpoke,
  },
  {
    icao: 'PARC',
    name: "Arctic Village",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 68.1147,
    lon: -145.579,
    ...drySpoke,
  },
  {
    icao: 'PARY',
    name: "Ruby",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 64.7272,
    lon: -155.47,
    ...drySpoke,
  },
  {
    icao: 'PASA',
    name: "Savoonga",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 63.6864,
    lon: -170.493,
    ...drySpoke,
  },
  {
    icao: 'PASC',
    name: "Deadhorse",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 70.1947,
    lon: -148.465,
    ...drySpoke,
  },
  {
    icao: 'PASD',
    name: "Sand Point",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 55.3139,
    lon: -160.5221,
    ...drySpoke,
  },
  {
    icao: 'PASI',
    name: "Sitka Rocky Gutierrez",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 57.0471,
    lon: -135.362,
    ...drySpoke,
  },
  {
    icao: 'PASN',
    name: "St Paul Island",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 57.1663,
    lon: -170.2226,
    ...drySpoke,
  },
  {
    icao: 'PATQ',
    name: "Atqasuk Edward Burnell Sr Memorial",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 70.467,
    lon: -157.436,
    ...drySpoke,
  },
  {
    icao: 'PAUN',
    name: "Unalakleet",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 63.8884,
    lon: -160.799,
    ...drySpoke,
  },
  {
    icao: 'PAVD',
    name: "Valdez Pioneer Field",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 61.1327,
    lon: -146.2466,
    ...drySpoke,
  },
  {
    icao: 'PAWG',
    name: "Wrangell",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 56.4843,
    lon: -132.37,
    ...drySpoke,
  },
  {
    icao: 'PAWI',
    name: "Wainwright",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 70.638,
    lon: -159.995,
    ...drySpoke,
  },
  {
    icao: 'PAYA',
    name: "Yakutat",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 59.5087,
    lon: -139.6604,
    ...drySpoke,
  },
  {
    icao: 'PFYU',
    name: "Fort Yukon",
    region: 'US-AK',
    hubTier: 'spoke',
    lat: 66.5717,
    lon: -145.25,
    ...drySpoke,
  },
];

export const US_AK_CAREER_HUB_COUNT = 57;

export function assertUsAkCareerHubCatalog(): void {
  if (US_AK_CAREER_HUBS.length !== US_AK_CAREER_HUB_COUNT) {
    throw new Error(
      `US_AK_CAREER_HUBS length ${US_AK_CAREER_HUBS.length} !== ${US_AK_CAREER_HUB_COUNT}`,
    );
  }
  const seen = new Set<string>();
  for (const h of US_AK_CAREER_HUBS) {
    if (h.region !== 'US-AK') throw new Error(`${h.icao} must use region US-AK`);
    if (seen.has(h.icao)) throw new Error(`Duplicate Alaska hub ${h.icao}`);
    seen.add(h.icao);
  }
  if (!US_AK_CAREER_HUBS.some((h) => h.icao === 'PANC' && h.hubTier === 'major')) {
    throw new Error('US-AK catalog must include major PANC');
  }
}
