/**
 * China densify — Wave B/D commercial hubs (MSFS + SimBrief).
 * Merged into CN_CAREER_HUBS. No bush strips.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { CnCareerRegion } from './career-cn-hubs.js';

type CnDensifyHub = {
  icao: string;
  name: string;
  region: CnCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

/** CN densify (+22). */
export const CN_DENSIFY_HUBS: readonly CnDensifyHub[] = [
  {
    icao: 'ZBOW',
    name: "Baotou Donghe International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 40.56,
    lon: 109.997,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSYT',
    name: "Yantai Penglai International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 37.6572,
    lon: 120.9872,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZBDT',
    name: "Datong Yungang International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 40.06139,
    lon: 113.48051,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZLDH',
    name: "Dunhuang Mogao International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 40.16195,
    lon: 94.81283,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZHEC',
    name: "Ezhou Huahu International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 30.34118,
    lon: 115.03926,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZGKL',
    name: "Guilin Liangjiang International Airport",
    region: 'CN-W',
    hubTier: 'regional',
    lat: 25.21983,
    lon: 110.03955,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSOF',
    name: "Hefei Xinqiao International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 31.98779,
    lon: 116.9769,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSSH',
    name: "Huai'an Lianshui Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 33.79271,
    lon: 119.12666,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSTX',
    name: "Huangshan Tunxi International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 29.7333,
    lon: 118.256,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZBLA',
    name: "Hulunbuir Hailar Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 49.20862,
    lon: 119.8223,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZLJQ',
    name: "Jiayuguan International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 39.85905,
    lon: 98.33934,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZGOW',
    name: "Jieyang Chaoshan International Airport",
    region: 'CN-S',
    hubTier: 'regional',
    lat: 23.552,
    lon: 116.5033,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSJN',
    name: "Jinan Yaoqiang International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 36.8572,
    lon: 117.216,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZWSH',
    name: "Kashgar Laining International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 39.54227,
    lon: 76.02023,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZULS',
    name: "Lhasa Gonggar International Airport",
    region: 'CN-W',
    hubTier: 'regional',
    lat: 29.298,
    lon: 90.91195,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSLG',
    name: "Lianyungang Huaguoshan International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 34.41406,
    lon: 119.17899,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZPLJ',
    name: "Lijiang Sanyi International Airport",
    region: 'CN-W',
    hubTier: 'regional',
    lat: 26.67748,
    lon: 100.24494,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZHLY',
    name: "Luoyang Beijiao Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 34.7411,
    lon: 112.388,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSCN',
    name: "Nanchang Changbei International Airport",
    region: 'CN-E',
    hubTier: 'regional',
    lat: 28.86482,
    lon: 115.90271,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZBDS',
    name: "Ordos Ejin Horo International Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 39.49351,
    lon: 109.8599,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZYQQ',
    name: "Qiqihar Sanjiazi Airport",
    region: 'CN-N',
    hubTier: 'regional',
    lat: 47.22997,
    lon: 123.91418,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'ZSQZ',
    name: "Quanzhou Jinjiang International Airport",
    region: 'CN-S',
    hubTier: 'regional',
    lat: 24.79585,
    lon: 118.5886,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
];

export const CN_DENSIFY_HUB_COUNT = CN_DENSIFY_HUBS.length;
