/**
 * US commercial airports with scheduled service that were still outside the
 * career catalog. Medium fields are spokes. Large fields are regional.
 * Coords from OurAirports. Merged into US_CAREER_HUBS.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';

type ScheduledHub = {
  icao: string;
  name: string;
  region: 'US-W' | 'US-MT' | 'US-MW' | 'US-SC' | 'US-SE' | 'US-NE';
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.05, supplies: 1.0 },
  consume: { electronics: 0.85, machinery: 0.85, perishables: 0.9 },
} as const;

const dryRegional = {
  produce: { general: 1.15, supplies: 1.05, electronics: 0.95 },
  consume: { perishables: 0.95, machinery: 0.9 },
} as const;

/** US-W scheduled commercial fill (+12). */
export const US_W_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KAWO',
    name: "Arlington Municipal",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 48.1614,
    lon: -122.1584,
    ...drySpoke,
  },
  {
    icao: 'KCEC',
    name: "Jack Mc Namara Field",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 41.7789,
    lon: -124.2364,
    ...drySpoke,
  },
  {
    icao: 'KFHR',
    name: "Friday Harbor",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 48.5237,
    lon: -123.0246,
    ...drySpoke,
  },
  {
    icao: 'KHHR',
    name: "Jack Northrop Field Hawthorne Municipal",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 33.9228,
    lon: -118.335,
    ...drySpoke,
  },
  {
    icao: 'KIPL',
    name: "Imperial County",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 32.8354,
    lon: -115.574,
    ...drySpoke,
  },
  {
    icao: 'KMCE',
    name: "Merced Regional Macready Field",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.2847,
    lon: -120.514,
    ...drySpoke,
  },
  {
    icao: 'KOLM',
    name: "Olympia Regional",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.9694,
    lon: -122.903,
    ...drySpoke,
  },
  {
    icao: 'KORS',
    name: "Orcas Island",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 48.7082,
    lon: -122.91,
    ...drySpoke,
  },
  {
    icao: 'KPDT',
    name: "Eastern Oregon Regional Airport at Pendleton",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 45.6951,
    lon: -118.841,
    ...drySpoke,
  },
  {
    icao: 'KSBD',
    name: "San Bernardino International",
    region: 'US-W',
    hubTier: 'regional',
    lat: 34.0967,
    lon: -117.2366,
    ...dryRegional,
  },
  {
    icao: 'KSQL',
    name: "San Carlos",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.5131,
    lon: -122.2508,
    ...drySpoke,
  },
  {
    icao: 'KTIW',
    name: "Tacoma Narrows",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 47.2674,
    lon: -122.5773,
    ...drySpoke,
  },
];

/** US-MT scheduled commercial fill (+27). */
export const US_MT_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KALS',
    name: "San Luis Valley Regional Airport/Bergman Field",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 37.4349,
    lon: -105.867,
    ...drySpoke,
  },
  {
    icao: 'KBJC',
    name: "Rocky Mountain Metropolitan",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 39.9088,
    lon: -105.117,
    ...drySpoke,
  },
  {
    icao: 'KCEZ',
    name: "Cortez Municipal",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 37.303,
    lon: -108.628,
    ...drySpoke,
  },
  {
    icao: 'KCNM',
    name: "Cavern City Air Terminal",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 32.3375,
    lon: -104.263,
    ...drySpoke,
  },
  {
    icao: 'KCNY',
    name: "Canyonlands Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 38.755,
    lon: -109.755,
    ...drySpoke,
  },
  {
    icao: 'KCVN',
    name: "Clovis Municipal",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 34.4266,
    lon: -103.0788,
    ...drySpoke,
  },
  {
    icao: 'KGCC',
    name: "Northeast Wyoming Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 44.3489,
    lon: -105.539,
    ...drySpoke,
  },
  {
    icao: 'KGCN',
    name: "Grand Canyon National Park",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 35.9524,
    lon: -112.147,
    ...drySpoke,
  },
  {
    icao: 'KGDV',
    name: "Dawson Community",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 47.1377,
    lon: -104.8069,
    ...drySpoke,
  },
  {
    icao: 'KGGW',
    name: "Glasgow Valley County Airport Wokal Field",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 48.2125,
    lon: -106.615,
    ...drySpoke,
  },
  {
    icao: 'KGUP',
    name: "Gallup Municipal",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 35.5117,
    lon: -108.7882,
    ...drySpoke,
  },
  {
    icao: 'KHII',
    name: "Lake Havasu City",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 34.5705,
    lon: -114.3577,
    ...drySpoke,
  },
  {
    icao: 'KHOB',
    name: "Lea County Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 32.6875,
    lon: -103.217,
    ...drySpoke,
  },
  {
    icao: 'KHVR',
    name: "Havre City County",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 48.5414,
    lon: -109.7629,
    ...drySpoke,
  },
  {
    icao: 'KLAR',
    name: "Laramie Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 41.3121,
    lon: -105.675,
    ...drySpoke,
  },
  {
    icao: 'KLRU',
    name: "Las Cruces International",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 32.2894,
    lon: -106.922,
    ...drySpoke,
  },
  {
    icao: 'KMYL',
    name: "McCall Municipal",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 44.8888,
    lon: -116.1011,
    ...drySpoke,
  },
  {
    icao: 'KNYL',
    name: "Yuma International Airport / Marine Corps Air Station Yuma",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 32.6509,
    lon: -114.6094,
    ...drySpoke,
  },
  {
    icao: 'KOLF',
    name: "L M Clayton",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 48.0945,
    lon: -105.575,
    ...drySpoke,
  },
  {
    icao: 'KRIW',
    name: "Central Wyoming Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 43.0642,
    lon: -108.46,
    ...drySpoke,
  },
  {
    icao: 'KSDY',
    name: "Sidney - Richland Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 47.7051,
    lon: -104.1944,
    ...drySpoke,
  },
  {
    icao: 'KSKX',
    name: "Taos Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 36.4525,
    lon: -105.6775,
    ...drySpoke,
  },
  {
    icao: 'KSMN',
    name: "Lemhi County",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 45.1222,
    lon: -113.882,
    ...drySpoke,
  },
  {
    icao: 'KSOW',
    name: "Show Low Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 34.2641,
    lon: -110.0071,
    ...drySpoke,
  },
  {
    icao: 'KSVC',
    name: "Grant County",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 32.6367,
    lon: -108.1547,
    ...drySpoke,
  },
  {
    icao: 'KVEL',
    name: "Vernal Regional",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 40.4362,
    lon: -109.5117,
    ...drySpoke,
  },
  {
    icao: 'KWYS',
    name: "Yellowstone",
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 44.6884,
    lon: -111.118,
    ...drySpoke,
  },
];

/** US-MW scheduled commercial fill (+56). */
export const US_MW_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KABR',
    name: "Aberdeen Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.4491,
    lon: -98.4218,
    ...drySpoke,
  },
  {
    icao: 'KAIA',
    name: "Alliance Municipal",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.0525,
    lon: -102.804,
    ...drySpoke,
  },
  {
    icao: 'KALO',
    name: "Waterloo Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.5571,
    lon: -92.4003,
    ...drySpoke,
  },
  {
    icao: 'KAPN',
    name: "Alpena County Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.0781,
    lon: -83.5603,
    ...drySpoke,
  },
  {
    icao: 'KATY',
    name: "Watertown Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 44.914,
    lon: -97.1547,
    ...drySpoke,
  },
  {
    icao: 'KBBG',
    name: "Branson",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 36.5321,
    lon: -93.2005,
    ...drySpoke,
  },
  {
    icao: 'KBFF',
    name: "Western Neb. Rgnl/William B. Heilig",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.874,
    lon: -103.596,
    ...drySpoke,
  },
  {
    icao: 'KBLV',
    name: "Scott AFB/Midamerica",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 38.5452,
    lon: -89.8352,
    ...drySpoke,
  },
  {
    icao: 'KBRD',
    name: "Brainerd Lakes Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 46.4029,
    lon: -94.1297,
    ...drySpoke,
  },
  {
    icao: 'KBRL',
    name: "Southeast Iowa Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.7832,
    lon: -91.1255,
    ...drySpoke,
  },
  {
    icao: 'KCDR',
    name: "Chadron Municipal",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.8376,
    lon: -103.095,
    ...drySpoke,
  },
  {
    icao: 'KCGI',
    name: "Cape Girardeau Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.2253,
    lon: -89.5708,
    ...drySpoke,
  },
  {
    icao: 'KCIU',
    name: "Chippewa County International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 46.242,
    lon: -84.4621,
    ...drySpoke,
  },
  {
    icao: 'KCMX',
    name: "Houghton County Memorial",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 47.1684,
    lon: -88.4891,
    ...drySpoke,
  },
  {
    icao: 'KDBQ',
    name: "Dubuque Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.402,
    lon: -90.7095,
    ...drySpoke,
  },
  {
    icao: 'KDDC',
    name: "Dodge City Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.7634,
    lon: -99.9656,
    ...drySpoke,
  },
  {
    icao: 'KDEC',
    name: "Decatur",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 39.8346,
    lon: -88.8657,
    ...drySpoke,
  },
  {
    icao: 'KDVL',
    name: "Devils Lake Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 48.1155,
    lon: -98.9088,
    ...drySpoke,
  },
  {
    icao: 'KEAR',
    name: "Kearney Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.727,
    lon: -99.0068,
    ...drySpoke,
  },
  {
    icao: 'KEAU',
    name: "Chippewa Valley Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 44.8658,
    lon: -91.4843,
    ...drySpoke,
  },
  {
    icao: 'KESC',
    name: "Delta County",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.7232,
    lon: -87.0886,
    ...drySpoke,
  },
  {
    icao: 'KFOD',
    name: "Fort Dodge Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.5526,
    lon: -94.1912,
    ...drySpoke,
  },
  {
    icao: 'KGCK',
    name: "Garden City Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.9275,
    lon: -100.724,
    ...drySpoke,
  },
  {
    icao: 'KGRI',
    name: "Central Nebraska Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.9675,
    lon: -98.3096,
    ...drySpoke,
  },
  {
    icao: 'KGYY',
    name: "Gary/Chicago International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.6171,
    lon: -87.4132,
    ...drySpoke,
  },
  {
    icao: 'KHIB',
    name: "Range Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 47.3848,
    lon: -92.8369,
    ...drySpoke,
  },
  {
    icao: 'KHYS',
    name: "Hays Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 38.8445,
    lon: -99.2731,
    ...drySpoke,
  },
  {
    icao: 'KIMT',
    name: "Ford",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.8191,
    lon: -88.1146,
    ...drySpoke,
  },
  {
    icao: 'KINL',
    name: "Falls International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 48.5662,
    lon: -93.4031,
    ...drySpoke,
  },
  {
    icao: 'KIRK',
    name: "Kirksville Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.0935,
    lon: -92.5449,
    ...drySpoke,
  },
  {
    icao: 'KJLN',
    name: "Joplin Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.1518,
    lon: -94.4983,
    ...drySpoke,
  },
  {
    icao: 'KJMS',
    name: "Jamestown Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 46.9297,
    lon: -98.6782,
    ...drySpoke,
  },
  {
    icao: 'KLBF',
    name: "North Platte Regional Airport Lee Bird Field",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.1262,
    lon: -100.684,
    ...drySpoke,
  },
  {
    icao: 'KLBL',
    name: "Liberal Mid-America Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.0442,
    lon: -100.96,
    ...drySpoke,
  },
  {
    icao: 'KLSE',
    name: "La Crosse Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 43.879,
    lon: -91.2567,
    ...drySpoke,
  },
  {
    icao: 'KLUK',
    name: "Cincinnati Municipal Airport Lunken Field",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 39.1024,
    lon: -84.4189,
    ...drySpoke,
  },
  {
    icao: 'KMBS',
    name: "MBS International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 43.5332,
    lon: -84.0831,
    ...drySpoke,
  },
  {
    icao: 'KMCK',
    name: "McCook Ben Nelson Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.2078,
    lon: -100.5928,
    ...drySpoke,
  },
  {
    icao: 'KMCW',
    name: "Mason City Municipal",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 43.1598,
    lon: -93.3297,
    ...drySpoke,
  },
  {
    icao: 'KMGC',
    name: "Michigan City Municipal",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.7033,
    lon: -86.8212,
    ...drySpoke,
  },
  {
    icao: 'KMHK',
    name: "Manhattan Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 39.141,
    lon: -96.6708,
    ...drySpoke,
  },
  {
    icao: 'KMKG',
    name: "Muskegon County",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 43.1695,
    lon: -86.2382,
    ...drySpoke,
  },
  {
    icao: 'KMWA',
    name: "Veterans Airport of Southern Illinois",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.7512,
    lon: -89.0166,
    ...drySpoke,
  },
  {
    icao: 'KOWB',
    name: "Owensboro Daviess County",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.7401,
    lon: -87.1668,
    ...drySpoke,
  },
  {
    icao: 'KPAH',
    name: "Barkley Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.0608,
    lon: -88.7738,
    ...drySpoke,
  },
  {
    icao: 'KPCW',
    name: "Erie-Ottawa International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.5156,
    lon: -82.8683,
    ...drySpoke,
  },
  {
    icao: 'KPIR',
    name: "Pierre Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 44.3827,
    lon: -100.286,
    ...drySpoke,
  },
  {
    icao: 'KPLN',
    name: "Pellston Regional Airport of Emmet County",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.5709,
    lon: -84.7967,
    ...drySpoke,
  },
  {
    icao: 'KRHI',
    name: "Rhinelander Oneida County",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.6312,
    lon: -89.4675,
    ...drySpoke,
  },
  {
    icao: 'KSAW',
    name: "Marquette Sawyer Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 46.3515,
    lon: -87.3959,
    ...drySpoke,
  },
  {
    icao: 'KSLN',
    name: "Salina Municipal",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 38.791,
    lon: -97.6522,
    ...drySpoke,
  },
  {
    icao: 'KSTC',
    name: "Saint Cloud Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 45.5466,
    lon: -94.0599,
    ...drySpoke,
  },
  {
    icao: 'KTBN',
    name: "Waynesville-St. Robert Regional Airport-Forney Field",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.7416,
    lon: -92.1407,
    ...drySpoke,
  },
  {
    icao: 'KTVF',
    name: "Thief River Falls Regional",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 48.0657,
    lon: -96.185,
    ...drySpoke,
  },
  {
    icao: 'KUIN',
    name: "Quincy Regional Airport Baldwin Field",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 39.9427,
    lon: -91.1946,
    ...drySpoke,
  },
  {
    icao: 'KXWA',
    name: "Williston Basin International",
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 48.2609,
    lon: -103.7512,
    ...drySpoke,
  },
];

/** US-SC scheduled commercial fill (+13). */
export const US_SC_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KEDC',
    name: "Austin Executive",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 30.398,
    lon: -97.5669,
    ...drySpoke,
  },
  {
    icao: 'KELD',
    name: "South Arkansas Regional Airport at Goodwin Field",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.221,
    lon: -92.8133,
    ...drySpoke,
  },
  {
    icao: 'KFTW',
    name: "Fort Worth Meacham International",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.8199,
    lon: -97.3608,
    ...drySpoke,
  },
  {
    icao: 'KGLH',
    name: "Mid Delta Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.4829,
    lon: -90.9856,
    ...drySpoke,
  },
  {
    icao: 'KGTR',
    name: "Golden Triangle Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.4503,
    lon: -88.5914,
    ...drySpoke,
  },
  {
    icao: 'KHOT',
    name: "Memorial Field",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 34.4788,
    lon: -93.0963,
    ...drySpoke,
  },
  {
    icao: 'KHRO',
    name: "Boone County",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 36.2615,
    lon: -93.1547,
    ...drySpoke,
  },
  {
    icao: 'KJBR',
    name: "Jonesboro Municipal",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 35.8317,
    lon: -90.6464,
    ...drySpoke,
  },
  {
    icao: 'KMEI',
    name: "Key Field / Meridian Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.3326,
    lon: -88.7519,
    ...drySpoke,
  },
  {
    icao: 'KMWL',
    name: "Mineral Wells Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.7816,
    lon: -98.0602,
    ...drySpoke,
  },
  {
    icao: 'KPIB',
    name: "Hattiesburg Laurel Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 31.4671,
    lon: -89.3371,
    ...drySpoke,
  },
  {
    icao: 'KSWO',
    name: "Stillwater Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 36.1621,
    lon: -97.0856,
    ...drySpoke,
  },
  {
    icao: 'KVCT',
    name: "Victoria Regional",
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 28.8526,
    lon: -96.9185,
    ...drySpoke,
  },
];

/** US-SE scheduled commercial fill (+19). */
export const US_SE_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KABY',
    name: "Southwest Georgia Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 31.5329,
    lon: -84.1962,
    ...drySpoke,
  },
  {
    icao: 'KBKW',
    name: "Raleigh County Memorial",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 37.7873,
    lon: -81.1242,
    ...drySpoke,
  },
  {
    icao: 'KBQK',
    name: "Brunswick Golden Isles",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 31.2588,
    lon: -81.4665,
    ...drySpoke,
  },
  {
    icao: 'KDHN',
    name: "Dothan Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 31.3213,
    lon: -85.4496,
    ...drySpoke,
  },
  {
    icao: 'KDTS',
    name: "Destin Executive",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 30.4001,
    lon: -86.4715,
    ...drySpoke,
  },
  {
    icao: 'KHXD',
    name: "Hilton Head",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 32.2244,
    lon: -80.6975,
    ...drySpoke,
  },
  {
    icao: 'KJQF',
    name: "Concord-Padgett Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 35.3878,
    lon: -80.7091,
    ...drySpoke,
  },
  {
    icao: 'KLAL',
    name: "Lakeland Linder International",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 27.9893,
    lon: -82.0207,
    ...drySpoke,
  },
  {
    icao: 'KLWB',
    name: "Greenbrier Valley",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 37.8579,
    lon: -80.4004,
    ...drySpoke,
  },
  {
    icao: 'KMCN',
    name: "Middle Georgia Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 32.6928,
    lon: -83.6492,
    ...drySpoke,
  },
  {
    icao: 'KMKL',
    name: "McKellar-Sipes Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 35.5999,
    lon: -88.9156,
    ...drySpoke,
  },
  {
    icao: 'KMSL',
    name: "Northwest Alabama Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 34.7451,
    lon: -87.613,
    ...drySpoke,
  },
  {
    icao: 'KOAJ',
    name: "Albert J Ellis",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 34.8292,
    lon: -77.6121,
    ...drySpoke,
  },
  {
    icao: 'KOPF',
    name: "Miami-Opa Locka Executive",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 25.907,
    lon: -80.2784,
    ...drySpoke,
  },
  {
    icao: 'KPDK',
    name: "DeKalb Peachtree",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 33.8763,
    lon: -84.3021,
    ...drySpoke,
  },
  {
    icao: 'KPGV',
    name: "Pitt-Greenville",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 35.6355,
    lon: -77.3843,
    ...drySpoke,
  },
  {
    icao: 'KSGJ',
    name: "Northeast Florida Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 29.9592,
    lon: -81.3398,
    ...drySpoke,
  },
  {
    icao: 'KVLD',
    name: "Valdosta Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 30.7825,
    lon: -83.2767,
    ...drySpoke,
  },
  {
    icao: 'KVRB',
    name: "Vero Beach Regional",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 27.6556,
    lon: -80.4179,
    ...drySpoke,
  },
];

/** US-NE scheduled commercial fill (+27). */
export const US_NE_SCHEDULED_HUBS: readonly ScheduledHub[] = [
  {
    icao: 'KAOO',
    name: "Altoona Blair County",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.2964,
    lon: -78.32,
    ...drySpoke,
  },
  {
    icao: 'KART',
    name: "Watertown International",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 43.9919,
    lon: -76.0217,
    ...drySpoke,
  },
  {
    icao: 'KAUG',
    name: "Augusta State",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.3206,
    lon: -69.7973,
    ...drySpoke,
  },
  {
    icao: 'KBED',
    name: "Laurence G Hanscom Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 42.47,
    lon: -71.289,
    ...drySpoke,
  },
  {
    icao: 'KBFD',
    name: "Bradford Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.8031,
    lon: -78.6401,
    ...drySpoke,
  },
  {
    icao: 'KDOV',
    name: "Dover Civil Air Terminal/Dover Air Force Base",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 39.1295,
    lon: -75.466,
    ...drySpoke,
  },
  {
    icao: 'KDUJ',
    name: "DuBois Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.1783,
    lon: -78.8987,
    ...drySpoke,
  },
  {
    icao: 'KEWB',
    name: "New Bedford Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.6761,
    lon: -70.9569,
    ...drySpoke,
  },
  {
    icao: 'KIPT',
    name: "Williamsport Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.2421,
    lon: -76.9224,
    ...drySpoke,
  },
  {
    icao: 'KJST',
    name: "John Murtha Johnstown Cambria County",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.3161,
    lon: -78.8339,
    ...drySpoke,
  },
  {
    icao: 'KLBE',
    name: "Arnold Palmer Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.2759,
    lon: -79.4048,
    ...drySpoke,
  },
  {
    icao: 'KLEB',
    name: "Lebanon Municipal",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 43.6261,
    lon: -72.3042,
    ...drySpoke,
  },
  {
    icao: 'KLNS',
    name: "Lancaster",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.1217,
    lon: -76.2961,
    ...drySpoke,
  },
  {
    icao: 'KLYH',
    name: "Lynchburg Regional Airport - Preston Glenn Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 37.3267,
    lon: -79.2004,
    ...drySpoke,
  },
  {
    icao: 'KMGW',
    name: "Morgantown Municipal Airport Walter L. (Bill) Hart Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 39.6433,
    lon: -79.9176,
    ...drySpoke,
  },
  {
    icao: 'KMSS',
    name: "Massena International Airport Richards Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.9362,
    lon: -74.8443,
    ...drySpoke,
  },
  {
    icao: 'KOGS',
    name: "Ogdensburg International",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.6819,
    lon: -75.4655,
    ...drySpoke,
  },
  {
    icao: 'KOXB',
    name: "Ocean City Municipal",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.3104,
    lon: -75.124,
    ...drySpoke,
  },
  {
    icao: 'KPBG',
    name: "Plattsburgh International",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.6509,
    lon: -73.4681,
    ...drySpoke,
  },
  {
    icao: 'KPKB',
    name: "Mid Ohio Valley Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 39.3451,
    lon: -81.4392,
    ...drySpoke,
  },
  {
    icao: 'KPQI',
    name: "Presque Isle International",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 46.689,
    lon: -68.0448,
    ...drySpoke,
  },
  {
    icao: 'KRKD',
    name: "Knox County Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.0601,
    lon: -69.0992,
    ...drySpoke,
  },
  {
    icao: 'KRUT',
    name: "Rutland - Southern Vermont Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 43.5294,
    lon: -72.9496,
    ...drySpoke,
  },
  {
    icao: 'KSHD',
    name: "Shenandoah Valley Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.2638,
    lon: -78.8964,
    ...drySpoke,
  },
  {
    icao: 'KSLK',
    name: "Adirondack Regional",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.3869,
    lon: -74.2046,
    ...drySpoke,
  },
  {
    icao: 'KUUU',
    name: "Newport State",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.5322,
    lon: -71.281,
    ...drySpoke,
  },
  {
    icao: 'KWST',
    name: "Westerly State",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.3496,
    lon: -71.8034,
    ...drySpoke,
  },
];

export const US_SCHEDULED_HUB_COUNT =
  US_W_SCHEDULED_HUBS.length +
  US_MT_SCHEDULED_HUBS.length +
  US_MW_SCHEDULED_HUBS.length +
  US_SC_SCHEDULED_HUBS.length +
  US_SE_SCHEDULED_HUBS.length +
  US_NE_SCHEDULED_HUBS.length;
