/**
 * France densify — commercial LF* airports (MSFS + SimBrief).
 * Merged into FR_CAREER_HUBS.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { FrCareerRegion } from './career-fr-hubs.js';

type FrDensifyHub = {
  icao: string;
  name: string;
  region: FrCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.1, supplies: 1.0, perishables: 1.05 },
  consume: { electronics: 0.9, machinery: 0.85 },
} as const;

const agro = {
  produce: { perishables: 1.35, general: 1.1, supplies: 1.0 },
  consume: { electronics: 0.9, machinery: 0.85 },
} as const;

const city = {
  produce: { general: 1.2, electronics: 1.1, supplies: 1.0 },
  consume: { perishables: 1.1, machinery: 0.9 },
} as const;

/** FR densify (+23) → 37 total (incl. Wave 1 +10; +2 redirected from BE). */
export const FR_DENSIFY_HUBS: readonly FrDensifyHub[] = [
  {
    icao: 'LFRN',
    name: 'Rennes Saint Jacques',
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.0695,
    lon: -1.73479,
    ...agro,
  },
  {
    icao: 'LFQQ',
    name: 'Lille Lesquin',
    region: 'FR-N',
    hubTier: 'regional',
    lat: 50.5619,
    lon: 3.08944,
    ...city,
  },
  {
    icao: 'LFRH',
    name: 'Lorient Lann Bihoue',
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 47.7606,
    lon: -3.44,
    ...drySpoke,
  },
  {
    icao: 'LFBI',
    name: 'Poitiers Biard',
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 46.5877,
    lon: 0.306667,
    ...agro,
  },
  {
    icao: 'LFBH',
    name: 'La Rochelle Ile de Re',
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 46.1792,
    lon: -1.19528,
    produce: { perishables: 1.25, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFLS',
    name: 'Grenoble Isere',
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 45.3629,
    lon: 5.32937,
    ...city,
  },
  {
    icao: 'LFMT',
    name: 'Montpellier Mediterranee',
    region: 'FR-S',
    hubTier: 'regional',
    lat: 43.5763,
    lon: 3.96301,
    ...agro,
  },
  {
    icao: 'LFBZ',
    name: 'Biarritz Pays Basque',
    region: 'FR-S',
    hubTier: 'spoke',
    lat: 43.4683,
    lon: -1.52333,
    produce: { perishables: 1.2, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.95, machinery: 0.9 },
  },
  {
    icao: 'LFJL',
    name: 'Metz Nancy Lorraine',
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 48.9781,
    lon: 6.24861,
    ...city,
  },
  {
    icao: 'LFTH',
    name: 'Toulon Hyeres',
    region: 'FR-S',
    hubTier: 'spoke',
    lat: 43.0973,
    lon: 6.14603,
    ...drySpoke,
  },
  {
    icao: 'LFKB',
    name: "Bastia Poretta",
    region: 'FR-S',
    hubTier: 'regional',
    lat: 42.5527,
    lon: 9.48373,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'LFKF',
    name: "Figari Sud-Corse Airport",
    region: 'FR-S',
    hubTier: 'regional',
    lat: 41.50185,
    lon: 9.09709,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'LFKJ',
    name: "Ajaccio Napoléon Bonaparte airport",
    region: 'FR-S',
    hubTier: 'regional',
    lat: 41.9236,
    lon: 8.80292,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  // Wave 1 EU-1 densify (+10; includes +2 redirected from BE)
  {
    icao: 'LFOT',
    name: 'Tours Val de Loire',
    region: 'FR-C',
    hubTier: 'regional',
    lat: 47.4322,
    lon: 0.727606,
    ...city,
  },
  {
    icao: 'LFLB',
    name: 'Chambery Aix-les-Bains',
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 45.6381,
    lon: 5.88028,
    ...city,
  },
  {
    icao: 'LFLP',
    name: 'Annecy Meythet',
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 45.9306,
    lon: 6.10639,
    ...city,
  },
  {
    icao: 'LFMK',
    name: 'Carcassonne Salvaza',
    region: 'FR-S',
    hubTier: 'spoke',
    lat: 43.2159,
    lon: 2.30632,
    ...agro,
  },
  {
    icao: 'LFMP',
    name: 'Perpignan Rivesaltes',
    region: 'FR-S',
    hubTier: 'regional',
    lat: 42.7404,
    lon: 2.87067,
    ...agro,
  },
  {
    icao: 'LFBE',
    name: 'Bergerac Dordogne Perigord',
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 44.8253,
    lon: 0.518611,
    ...agro,
  },
  {
    icao: 'LFBL',
    name: 'Limoges Bellegarde',
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 45.8628,
    lon: 1.17944,
    ...city,
  },
  {
    icao: 'LFRD',
    name: 'Dinard Pleurtuit Saint-Malo',
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.5877,
    lon: -2.07846,
    ...drySpoke,
  },
  {
    icao: 'LFOH',
    name: 'Le Havre Octeville',
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 49.5339,
    lon: 0.088056,
    ...drySpoke,
  },
  {
    icao: 'LFRZ',
    name: 'Saint-Nazaire Montoir',
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 47.3122,
    lon: -2.14944,
    produce: { machinery: 1.25, general: 1.1, supplies: 1.0 },
    consume: { perishables: 1.05, electronics: 0.9 },
  },


  // Wave 2 EU-1 densify (+17)
  {
    icao: 'LFPB',
    name: "Paris-Le Bourget International Airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.96228,
    lon: 2.43654,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'LFPN',
    name: "Toussus-le-Noble Airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.7519,
    lon: 2.10619,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'LFRG',
    name: "Deauville Normandie airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 49.36524,
    lon: 0.15448,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'LFRK',
    name: "Caen Carpiquet airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 49.17678,
    lon: -0.45488,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'LFOK',
    name: "Chalons Vatry airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.77333,
    lon: 4.20611,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'LFGJ',
    name: "Dole Tavaux Airport",
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 47.03896,
    lon: 5.42759,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFLY',
    name: "Lyon Bron Airport",
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 45.72795,
    lon: 4.94399,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'LFMH',
    name: "Saint-Étienne-Bouthéon Airport",
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 45.5406,
    lon: 4.29639,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'LFMQ',
    name: "Le Castellet Airport",
    region: 'FR-S',
    hubTier: 'spoke',
    lat: 43.2525,
    lon: 5.78519,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'LFCK',
    name: "Castres Mazamet Airport",
    region: 'FR-S',
    hubTier: 'spoke',
    lat: 43.5563,
    lon: 2.28918,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFAT',
    name: "Le Touquet-Côte d'Opale Airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 50.51828,
    lon: 1.62166,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'LFRO',
    name: "Lannion Airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.7544,
    lon: -3.47166,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'LFRT',
    name: "Saint-Brieuc-Armor Airport",
    region: 'FR-N',
    hubTier: 'spoke',
    lat: 48.53863,
    lon: -2.85352,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFQB',
    name: "Troyes-Barberey Airport",
    region: 'FR-E',
    hubTier: 'spoke',
    lat: 48.3221,
    lon: 4.0167,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFLN',
    name: "Saint-Yan Airport",
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 46.41402,
    lon: 4.01418,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFAC',
    name: "Calais Marck Airport",
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 50.9621,
    lon: 1.95476,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'LFAG',
    name: "Péronne Saint-Quentin Airfield",
    region: 'FR-C',
    hubTier: 'spoke',
    lat: 49.86887,
    lon: 3.02957,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
];

export const FR_DENSIFY_HUB_COUNT = FR_DENSIFY_HUBS.length;
