/**
 * Canada densify — commercial CY* airports (MSFS + SimBrief).
 * Merged into CA_CAREER_HUBS. No bush strips.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { CaCareerRegion } from './career-ca-hubs.js';

type CaDensifyHub = {
  icao: string;
  name: string;
  region: CaCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.1, supplies: 1.0, perishables: 1.05 },
  consume: { electronics: 0.9, machinery: 0.85 },
} as const;

const city = {
  produce: { general: 1.2, electronics: 1.1, supplies: 1.0 },
  consume: { perishables: 1.1, machinery: 0.9 },
} as const;

/** CA densify (+53) → 106 total. */
export const CA_DENSIFY_HUBS: readonly CaDensifyHub[] = [
  {
    icao: 'CYTZ',
    name: 'Billy Bishop Toronto City',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 43.6275,
    lon: -79.3962,
    ...drySpoke,
  },
  {
    icao: 'CYMX',
    name: 'Montreal Mirabel',
    region: 'CA-QC',
    hubTier: 'regional',
    lat: 45.6795,
    lon: -74.0053,
    ...city,
  },
  {
    icao: 'CYSB',
    name: 'Greater Sudbury',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 46.625,
    lon: -80.7989,
    ...drySpoke,
  },
  {
    icao: 'CYGK',
    name: 'Kingston',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 44.2253,
    lon: -76.5969,
    ...drySpoke,
  },
  {
    icao: 'CYQT',
    name: 'Thunder Bay',
    region: 'CA-ON',
    hubTier: 'regional',
    lat: 48.3719,
    lon: -89.3239,
    ...city,
  },
  {
    icao: 'CYQL',
    name: 'Lethbridge',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 49.6303,
    lon: -112.7997,
    ...drySpoke,
  },
  {
    icao: 'CYMM',
    name: 'Fort McMurray',
    region: 'CA-PR',
    hubTier: 'regional',
    lat: 56.6533,
    lon: -111.2219,
    ...city,
  },
  {
    icao: 'CYXC',
    name: 'Cranbrook',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 49.6108,
    lon: -115.7819,
    ...drySpoke,
  },
  {
    icao: 'CYCG',
    name: 'Castlegar',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 49.2964,
    lon: -117.6325,
    ...drySpoke,
  },
  {
    icao: 'CYXJ',
    name: 'Fort St John',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 56.2381,
    lon: -120.7403,
    ...drySpoke,
  },
  {
    icao: 'CYDQ',
    name: 'Dawson Creek',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 55.7423,
    lon: -120.1831,
    ...drySpoke,
  },
  {
    icao: 'CYYE',
    name: 'Fort Nelson',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 58.8364,
    lon: -122.5969,
    ...drySpoke,
  },
  {
    icao: 'CYZF',
    name: 'Yellowknife',
    region: 'CA-PR',
    hubTier: 'regional',
    lat: 62.4628,
    lon: -114.4403,
    ...city,
  },
  {
    icao: 'CYXY',
    name: 'Whitehorse',
    region: 'CA-W',
    hubTier: 'regional',
    lat: 60.7096,
    lon: -135.0681,
    ...city,
  },
  {
    icao: 'CYFB',
    name: 'Iqaluit',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 63.7564,
    lon: -68.5558,
    ...drySpoke,
  },
  {
    icao: 'CYQX',
    name: 'Gander',
    region: 'CA-AT',
    hubTier: 'regional',
    lat: 48.9369,
    lon: -54.5681,
    ...city,
  },
  {
    icao: 'CYDF',
    name: 'Deer Lake NL',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 49.2108,
    lon: -57.3914,
    ...drySpoke,
  },
  {
    icao: 'CYYG',
    name: 'Charlottetown',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 46.29,
    lon: -63.1211,
    ...drySpoke,
  },
  {
    icao: 'CYQI',
    name: 'Yarmouth',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 43.8269,
    lon: -66.0881,
    ...drySpoke,
  },
  {
    icao: 'CYZV',
    name: 'Sept-Iles',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 50.2233,
    lon: -66.2656,
    ...drySpoke,
  },
  {
    icao: 'CYBC',
    name: 'Baie-Comeau',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 49.1325,
    lon: -68.2044,
    ...drySpoke,
  },
  {
    icao: 'CYGP',
    name: 'Gaspe',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 48.7753,
    lon: -64.4786,
    ...drySpoke,
  },
  {
    icao: 'CYGR',
    name: 'Iles-de-la-Madeleine',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 47.4247,
    lon: -61.7781,
    ...drySpoke,
  },
  {
    icao: 'CYSC',
    name: 'Sherbrooke',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 45.4386,
    lon: -71.6914,
    ...drySpoke,
  },
  {
    icao: 'CYTH',
    name: 'Thompson',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 55.8011,
    lon: -97.8642,
    ...drySpoke,
  },
  {
    icao: 'CYBR',
    name: 'Brandon',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 49.91,
    lon: -99.9519,
    ...drySpoke,
  },
  {
    icao: 'CYAZ',
    name: 'Tofino',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 49.0822,
    lon: -125.7728,
    ...drySpoke,
  },
  {
    icao: 'CYYR',
    name: 'Goose Bay',
    region: 'CA-AT',
    hubTier: 'regional',
    lat: 53.3192,
    lon: -60.4258,
    ...city,
  },
  {
    icao: 'CYJT',
    name: 'Stephenville',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 48.5434,
    lon: -58.5529,
    ...drySpoke,
  },
  {
    icao: 'CYWK',
    name: 'Wabush',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 52.9219,
    lon: -66.8644,
    ...drySpoke,
  },
  {
    icao: 'CYAY',
    name: 'St Anthony',
    region: 'CA-AT',
    hubTier: 'spoke',
    lat: 51.3919,
    lon: -56.0832,
    ...drySpoke,
  },
  {
    icao: 'CYVO',
    name: "Val-d'Or",
    region: 'CA-QC',
    hubTier: 'regional',
    lat: 48.0533,
    lon: -77.7828,
    ...city,
  },
  {
    icao: 'CYND',
    name: 'Ottawa Gatineau',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 45.5217,
    lon: -75.5636,
    ...drySpoke,
  },
  {
    icao: 'CYYY',
    name: 'Mont-Joli',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 48.6086,
    lon: -68.2081,
    ...drySpoke,
  },
  {
    icao: 'CYBX',
    name: 'Blanc-Sablon',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 51.4436,
    lon: -57.1853,
    ...drySpoke,
  },
  {
    icao: 'CYGV',
    name: 'Havre-Saint-Pierre',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 50.2819,
    lon: -63.6114,
    ...drySpoke,
  },
  {
    icao: 'CYGL',
    name: 'La Grande Riviere',
    region: 'CA-QC',
    hubTier: 'spoke',
    lat: 53.6253,
    lon: -77.7042,
    ...drySpoke,
  },
  {
    icao: 'CYXL',
    name: 'Sioux Lookout',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 50.1139,
    lon: -91.9053,
    ...drySpoke,
  },
  {
    icao: 'CYQK',
    name: 'Kenora',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 49.7883,
    lon: -94.3631,
    ...drySpoke,
  },
  {
    icao: 'CYHD',
    name: 'Dryden',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 49.8317,
    lon: -92.7442,
    ...drySpoke,
  },
  {
    icao: 'CYRL',
    name: 'Red Lake',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 51.0669,
    lon: -93.7931,
    ...drySpoke,
  },
  {
    icao: 'CYSN',
    name: 'Niagara District',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 43.1916,
    lon: -79.1717,
    ...drySpoke,
  },
  {
    icao: 'CYZR',
    name: 'Sarnia Chris Hadfield',
    region: 'CA-ON',
    hubTier: 'spoke',
    lat: 42.9994,
    lon: -82.3089,
    ...drySpoke,
  },
  {
    icao: 'CYQD',
    name: 'The Pas',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 53.9714,
    lon: -101.091,
    ...drySpoke,
  },
  {
    icao: 'CYDN',
    name: 'Dauphin',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 51.1008,
    lon: -100.052,
    ...drySpoke,
  },
  {
    icao: 'CYPE',
    name: 'Peace River',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 56.2269,
    lon: -117.447,
    ...drySpoke,
  },
  {
    icao: 'CYOJ',
    name: 'High Level',
    region: 'CA-PR',
    hubTier: 'spoke',
    lat: 58.6214,
    lon: -117.165,
    ...drySpoke,
  },
  {
    icao: 'CYYQ',
    name: 'Churchill',
    region: 'CA-PR',
    hubTier: 'regional',
    lat: 58.7392,
    lon: -94.065,
    ...city,
  },
  {
    icao: 'CYRT',
    name: 'Rankin Inlet',
    region: 'CA-PR',
    hubTier: 'regional',
    lat: 62.8114,
    lon: -92.1158,
    ...city,
  },
  {
    icao: 'CYZT',
    name: 'Port Hardy',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 50.6806,
    lon: -127.367,
    ...drySpoke,
  },
  {
    icao: 'CYZP',
    name: 'Sandspit',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 53.2543,
    lon: -131.814,
    ...drySpoke,
  },
  {
    icao: 'CYWL',
    name: 'Williams Lake',
    region: 'CA-W',
    hubTier: 'spoke',
    lat: 52.1831,
    lon: -122.054,
    ...drySpoke,
  },
  {
    icao: 'CYEV',
    name: 'Inuvik Mike Zubko',
    region: 'CA-W',
    hubTier: 'regional',
    lat: 68.3042,
    lon: -133.483,
    ...city,
  },
];

export const CA_DENSIFY_HUB_COUNT = CA_DENSIFY_HUBS.length;
