/**
 * FAA locals used only as bush-trip endpoints (not Market/ferry hubs).
 * Coords from Activities PLN (prev User WP), except MSFS overrides in
 * data/msfs-bush-hub-overrides.json (+ profiles/career overlay).
 * Regenerated via scripts/gen-bush-trip-only-hubs.mjs — do not edit by hand.
 */
import type { UsCareerHubDef } from './career-us-hubs.js';

const tripOnlySpoke = {
  produce: { general: 0.4, supplies: 0.35 } as const,
  consume: { general: 0.4, supplies: 0.35 } as const,
};

export const US_BUSH_TRIP_ONLY_HUBS: readonly UsCareerHubDef[] = [
  {
    icao: '0O2',
    name: "Baker",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 35.1789,
    lon: -116.0785,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: '1Q2',
    name: "Spalding",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.7303,
    lon: -120.7111,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: '26A',
    name: "Ashland / Lineville",
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 33.2842,
    lon: -85.8086,
    bushTripOnly: true,
    msfsValidated: true,
    ...tripOnlySpoke,
  },
  {
    icao: '2G4',
    name: "Garrett County",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 39.5189,
    lon: -79.3542,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: '3Q0',
    name: "Mina",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.27,
    lon: -118.0964,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: '57NC',
    name: "Sossamon Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 35.4298,
    lon: -83.4878,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: '88NV',
    name: "Black Rock City",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.6584,
    lon: -119.3702,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'CA11',
    name: "McCloud Airstrip",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.0532,
    lon: -120.2563,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'CA35',
    name: "San Rafael",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.8304,
    lon: -122.5087,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'CA51',
    name: "Sea Ranch",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.7046,
    lon: -123.433,
    bushTripOnly: true,
    msfsValidated: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'H37',
    name: "Herlong",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.0283,
    lon: -120.1039,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'L06',
    name: "Furnace Creek",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 36.3646,
    lon: -116.8093,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'L61',
    name: "Shoshone",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 35.8729,
    lon: -116.2586,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'M45',
    name: "Alpine County",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.7756,
    lon: -119.8237,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'NC06',
    name: "Elk River",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 36.1045,
    lon: -82.1306,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'NV16',
    name: "Gerlach area / local",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.9871,
    lon: -119.8118,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'NV47',
    name: "New Farm / local",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 39.769,
    lon: -119.6855,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O22',
    name: "Columbia",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.1975,
    lon: -119.9811,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O24',
    name: "Lee Vining",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.0876,
    lon: -119.1824,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O26',
    name: "Lone Pine / Death Valley",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 36.5237,
    lon: -117.9752,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O39',
    name: "Ravendale",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.9083,
    lon: -120.1547,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O43',
    name: "Yerington Municipal",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 39.031,
    lon: -119.035,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O56',
    name: "California Pines / local",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.819,
    lon: -118.4772,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O57',
    name: "Bryant Field",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.9991,
    lon: -119.036,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O64',
    name: "Breckenridge",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 35.3627,
    lon: -118.8561,
    bushTripOnly: true,
    msfsValidated: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O67',
    name: "Manzanar",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 36.7372,
    lon: -118.145,
    bushTripOnly: true,
    msfsValidated: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O77',
    name: "Fallon / local",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.8051,
    lon: -118.7321,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O79',
    name: "Sierraville Dearwater",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 39.775,
    lon: -120.3102,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'O99',
    name: "Olancha / Grant Airpark",
    region: 'US-W',
    hubTier: 'spoke',
    lat: 36.1548,
    lon: -117.9606,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'WV09',
    name: "Mike Ferrell Field",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 37.4532,
    lon: -81.5191,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'WV30',
    name: "Rainelle",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 37.8431,
    lon: -80.724,
    bushTripOnly: true,
    ...tripOnlySpoke,
  },
  {
    icao: 'WV52',
    name: "Green Bank Observatory",
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.4332,
    lon: -79.8402,
    bushTripOnly: true,
    ...tripOnlySpoke,
  }
] as const;

