/**
 * Australia densify — Wave B/D commercial hubs (MSFS + SimBrief).
 * Merged into AU_CAREER_HUBS. No bush strips.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { AuCareerRegion } from './career-au-hubs.js';

type AuDensifyHub = {
  icao: string;
  name: string;
  region: AuCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

/** AU densify (+20). */
export const AU_DENSIFY_HUBS: readonly AuDensifyHub[] = [
  {
    icao: 'YBRM',
    name: "Broome International Airport",
    region: 'AU-W',
    hubTier: 'regional',
    lat: -17.94919,
    lon: 122.2283,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YBCG',
    name: "Gold Coast Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -28.16596,
    lon: 153.50664,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YBHI',
    name: "Broken Hill Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -32.0014,
    lon: 141.472,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YWLM',
    name: "Newcastle Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -32.79611,
    lon: 151.83503,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YPPD',
    name: "Port Hedland International Airport",
    region: 'AU-W',
    hubTier: 'regional',
    lat: -20.38279,
    lon: 118.62979,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YBSU',
    name: "Sunshine Coast Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -26.59332,
    lon: 153.08319,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YBWW',
    name: "Toowoomba Wellcamp Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -27.55833,
    lon: 151.79334,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'YABA',
    name: "Albany Airport",
    region: 'AU-W',
    hubTier: 'regional',
    lat: -34.94333,
    lon: 117.80889,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YMAY',
    name: "Albury Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -36.06676,
    lon: 146.95915,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBAS',
    name: "Alice Springs Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -23.80659,
    lon: 133.90343,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YARM',
    name: "Armidale Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -30.5281,
    lon: 151.617,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YAYE',
    name: "Ayers Rock Connellan Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -25.18591,
    lon: 130.97703,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBNA',
    name: "Ballina Byron Gateway Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -28.83324,
    lon: 153.56147,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBAR',
    name: "Barcaldine Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -23.56627,
    lon: 145.30209,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBTH',
    name: "Bathurst Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -33.40682,
    lon: 149.65116,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBIE',
    name: "Bedourie Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -24.3461,
    lon: 139.46001,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBDV',
    name: "Birdsville Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -25.8975,
    lon: 139.34801,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBCK',
    name: "Blackall Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -24.43168,
    lon: 145.42972,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBOU',
    name: "Boulia Airport",
    region: 'AU-E',
    hubTier: 'regional',
    lat: -22.9133,
    lon: 139.89999,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'YBKE',
    name: "Bourke Airport",
    region: 'AU-Q',
    hubTier: 'regional',
    lat: -30.0392,
    lon: 145.952,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },

  // Wave A Oceania densify (+18)
  {
    icao: 'YARA',
    name: "Ararat Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -37.30998,
    lon: 142.98869,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'YBCV',
    name: "Charleville Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -26.4133,
    lon: 146.26199,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBHM',
    name: "Hamilton Island Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -20.3581,
    lon: 148.952,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'YBLA',
    name: "Benalla Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -36.5519,
    lon: 146.007,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBMA',
    name: "Mount Isa Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -20.66638,
    lon: 139.48847,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'YBMK',
    name: "Mackay Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -21.17082,
    lon: 149.18259,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'YBNS',
    name: "Bairnsdale Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -37.88754,
    lon: 147.56938,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBPN',
    name: "Proserpine Whitsunday Coast Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -20.49442,
    lon: 148.55358,
    produce: { perishables: 1.15, general: 1.1, supplies: 1.05 },
    consume: { electronics: 1, machinery: 0.85 },
  },
  {
    icao: 'YBRK',
    name: "Rockhampton Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -23.38002,
    lon: 150.47536,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBRN',
    name: "Balranald Airport",
    region: 'AU-NT',
    hubTier: 'spoke',
    lat: -34.62483,
    lon: 143.57711,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBRW',
    name: "Brewarrina Airport",
    region: 'AU-W',
    hubTier: 'spoke',
    lat: -29.97579,
    lon: 146.81438,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'YBTL',
    name: "Townsville Airport / RAAF Base Townsville",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -19.2529,
    lon: 146.76651,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBUD',
    name: "Bundaberg Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -24.90504,
    lon: 152.32261,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBWP',
    name: "Weipa Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -12.67749,
    lon: 141.92262,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCAR',
    name: "Carnarvon Airport",
    region: 'AU-W',
    hubTier: 'spoke',
    lat: -24.88434,
    lon: 113.66639,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCBA',
    name: "Cobar Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -31.5383,
    lon: 145.79401,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCBB',
    name: "Coonabarabran Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -31.3325,
    lon: 149.267,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCBP',
    name: "Coober Pedy Airport",
    region: 'AU-S',
    hubTier: 'spoke',
    lat: -29.03831,
    lon: 134.72217,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },

  // Wave B Oceania densify (+17; +1 after AYBM→YCIN homolog swap)
  {
    icao: 'YBTI',
    name: "Bathurst Island Airport",
    region: 'AU-NT',
    hubTier: 'spoke',
    lat: -11.76497,
    lon: 130.61577,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YBTR',
    name: "Blackwater Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -23.6031,
    lon: 148.80701,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCCA',
    name: "Chinchilla Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -26.77195,
    lon: 150.61757,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCCY',
    name: "Cloncurry Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -20.6686,
    lon: 140.504,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCDU',
    name: "Ceduna Airport",
    region: 'AU-S',
    hubTier: 'spoke',
    lat: -32.1306,
    lon: 133.71001,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCEE',
    name: "Cleve Airport",
    region: 'AU-S',
    hubTier: 'spoke',
    lat: -33.7097,
    lon: 136.50501,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCFS',
    name: "Coffs Harbour Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -30.3206,
    lon: 153.116,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCKN',
    name: "Cooktown Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -15.44365,
    lon: 145.18322,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCMT',
    name: "Clermont Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -22.7731,
    lon: 147.621,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCMU',
    name: "Cunnamulla Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -28.03,
    lon: 145.62199,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCNM',
    name: "Coonamble Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -30.98095,
    lon: 148.37783,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCOE',
    name: "Coen Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -13.76113,
    lon: 143.11331,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCOM',
    name: "Cooma Snowy Mountains Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -36.30045,
    lon: 148.97241,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCOR',
    name: "Corowa Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -35.9947,
    lon: 146.357,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCRG',
    name: "Corryong Airport",
    region: 'AU-Q',
    hubTier: 'spoke',
    lat: -36.1828,
    lon: 147.888,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCTM',
    name: "Cootamundra Airport",
    region: 'AU-E',
    hubTier: 'spoke',
    lat: -34.62428,
    lon: 148.03664,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
  {
    icao: 'YCIN',
    name: "RAAF Base Curtin",
    region: 'AU-W',
    hubTier: 'spoke',
    lat: -17.58139,
    lon: 123.82833,
    produce: { general: 1.2, electronics: 1.1, supplies: 1 },
    consume: { perishables: 1.1, machinery: 0.9 },
  },
];

export const AU_DENSIFY_HUB_COUNT = AU_DENSIFY_HUBS.length;
