/**
 * Germany densify — commercial ED* airports (MSFS + SimBrief).
 * Spoke/regional belt; no new majors. Merged into DE_CAREER_HUBS.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { DeCareerRegion } from './career-de-hubs.js';

type DeDensifyHub = {
  icao: string;
  name: string;
  region: DeCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const industrial = {
  produce: { machinery: 1.3, electronics: 1.2, general: 1.15 },
  consume: { perishables: 1.05, supplies: 1.0 },
} as const;

const drySpoke = {
  produce: { general: 1.1, supplies: 1.0, perishables: 1.05 },
  consume: { electronics: 0.9, machinery: 0.85 },
} as const;

const city = {
  produce: { general: 1.2, electronics: 1.1, supplies: 1.0 },
  consume: { perishables: 1.1, machinery: 0.9 },
} as const;

/** DE densify (+22) → 34 total (incl. Wave 1 +7). */
export const DE_DENSIFY_HUBS: readonly DeDensifyHub[] = [
  {
    icao: 'EDDG',
    name: 'Munster Osnabruck',
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 52.1346,
    lon: 7.68483,
    ...industrial,
  },
  {
    icao: 'EDVE',
    name: 'Braunschweig Wolfsburg',
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 52.3192,
    lon: 10.5561,
    ...industrial,
  },
  {
    icao: 'EDHL',
    name: 'Lubeck Blankensee',
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 53.8054,
    lon: 10.7192,
    ...drySpoke,
  },
  {
    icao: 'EDLW',
    name: 'Dortmund',
    region: 'DE-W',
    hubTier: 'regional',
    lat: 51.5183,
    lon: 7.61224,
    ...industrial,
  },
  {
    icao: 'EDLV',
    name: 'Weeze',
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 51.6024,
    lon: 6.14217,
    ...drySpoke,
  },
  {
    icao: 'EDFH',
    name: 'Frankfurt Hahn',
    region: 'DE-W',
    hubTier: 'regional',
    lat: 49.9487,
    lon: 7.26389,
    produce: { general: 1.35, electronics: 1.15, machinery: 1.1 },
    consume: { perishables: 1.05, supplies: 1.0 },
  },
  {
    icao: 'EDDR',
    name: 'Saarbrucken',
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 49.2146,
    lon: 7.10951,
    ...city,
  },
  {
    icao: 'EDNY',
    name: 'Friedrichshafen',
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 47.6713,
    lon: 9.51149,
    ...drySpoke,
  },
  {
    icao: 'EDJA',
    name: 'Memmingen',
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 47.9888,
    lon: 10.2395,
    ...drySpoke,
  },
  {
    icao: 'EDSB',
    name: 'Karlsruhe Baden-Baden',
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 48.7794,
    lon: 8.0805,
    ...city,
  },
  {
    icao: 'EDDE',
    name: 'Erfurt Weimar',
    region: 'DE-E',
    hubTier: 'spoke',
    lat: 50.9798,
    lon: 10.9581,
    ...city,
  },
  {
    icao: 'EDAH',
    name: 'Heringsdorf',
    region: 'DE-E',
    hubTier: 'spoke',
    lat: 53.8787,
    lon: 14.1523,
    produce: { perishables: 1.2, general: 1.05, supplies: 1.0 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDHK',
    name: "Kiel Holtenau",
    region: 'DE-N',
    hubTier: 'regional',
    lat: 54.3795,
    lon: 10.1452,
    produce: {"general":1.1,"supplies":1,"perishables":1.05},
    consume: {"electronics":0.9,"machinery":0.85},
  },
  {
    icao: 'EDVK',
    name: "Kassel Airport",
    region: 'DE-W',
    hubTier: 'regional',
    lat: 51.41839,
    lon: 9.39164,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  {
    icao: 'EDLP',
    name: "Paderborn Lippstadt Airport",
    region: 'DE-W',
    hubTier: 'regional',
    lat: 51.61253,
    lon: 8.61746,
    produce: {"general":1.2,"electronics":1.1,"supplies":1},
    consume: {"perishables":1.1,"general":1,"machinery":0.9},
  },
  // Wave 1 EU-1 densify (+7)
  {
    // Homolog: EDFE=Egelsbach (~30 nm); Mannheim City in stock MSFS is EDFM
    icao: 'EDFM',
    name: 'Mannheim City',
    region: 'DE-W',
    hubTier: 'regional',
    lat: 49.4727,
    lon: 8.51426,
    ...city,
  },
  {
    icao: 'EDLN',
    name: 'Monchengladbach',
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 51.2303,
    lon: 6.50444,
    ...industrial,
  },
  {
    icao: 'EDGS',
    name: 'Siegerland',
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 50.7077,
    lon: 8.08297,
    ...drySpoke,
  },
  {
    icao: 'EDTL',
    name: 'Lahr Black Forest',
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 48.3693,
    lon: 7.82772,
    ...drySpoke,
  },
  {
    icao: 'EDXW',
    name: 'Sylt',
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 54.9132,
    lon: 8.34047,
    produce: { perishables: 1.2, general: 1.05, supplies: 1.0 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDBM',
    name: 'Magdeburg City',
    region: 'DE-E',
    hubTier: 'spoke',
    lat: 52.0736,
    lon: 11.6264,
    ...city,
  },
  {
    icao: 'EDXH',
    name: 'Helgoland Dune',
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 54.1853,
    lon: 7.91583,
    ...drySpoke,
  },


  // Wave 2 EU-1 densify (+14)
  {
    icao: 'EDMA',
    name: "Augsburg Airport",
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 48.42528,
    lon: 10.93167,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'EDMO',
    name: "Oberpfaffenhofen Airport",
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 48.0814,
    lon: 11.2831,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'EDQM',
    name: "Hof-Plauen Airport",
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 50.28854,
    lon: 11.85288,
    produce: { perishables: 1.35, general: 1.1, supplies: 1 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDTY',
    name: "Adolf Würth Airport",
    region: 'DE-S',
    hubTier: 'spoke',
    lat: 49.11833,
    lon: 9.78389,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'EDHI',
    name: "Hamburg-Finkenwerder Airport",
    region: 'DE-N',
    hubTier: 'spoke',
    lat: 53.53528,
    lon: 9.83556,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.15 },
    consume: { perishables: 1.05, supplies: 1 },
  },
  {
    icao: 'EDAC',
    name: "Leipzig–Altenburg Airport",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 50.98195,
    lon: 12.50639,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDBN',
    name: "Neubrandenburg Trollenhagen Airport",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 53.6022,
    lon: 13.306,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDBR',
    name: "Rothenburg/Görlitz Airfield",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 51.36333,
    lon: 14.95,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDFZ',
    name: "Mainz-Finthen Airfield",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 49.9675,
    lon: 8.14722,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDGE',
    name: "Eisenach-Kindel Airport",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 50.9916,
    lon: 10.47973,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDLI',
    name: "Bielefeld Airport",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 51.96472,
    lon: 8.54444,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDML',
    name: "Landshut Airfield",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 48.51202,
    lon: 12.03486,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDQA',
    name: "Bamberg-Breitenau Airfield",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 49.9204,
    lon: 10.91423,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
  {
    icao: 'EDQD',
    name: "Bayreuth Airport",
    region: 'DE-W',
    hubTier: 'spoke',
    lat: 49.985,
    lon: 11.64,
    produce: { general: 1.1, supplies: 1, perishables: 1.05 },
    consume: { electronics: 0.9, machinery: 0.85 },
  },
];

export const DE_DENSIFY_HUB_COUNT = DE_DENSIFY_HUBS.length;
