/**
 * Continental US densify batch — commercial Class B/C airports only
 * (stock MSFS + SimBrief Dispatch). Merged into US_CAREER_HUBS.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';

type DensifyHub = {
  icao: string;
  name: string;
  region: 'US-W' | 'US-MT' | 'US-MW' | 'US-SC' | 'US-SE' | 'US-NE';
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.05, supplies: 1.0 },
  consume: { electronics: 0.85, machinery: 0.85, perishables: 0.9 },
} as const;

const dryRegional = {
  produce: { general: 1.15, supplies: 1.05, electronics: 0.95 },
  consume: { perishables: 0.95, machinery: 0.9 },
} as const;

/** US-MW densify (+18). */
export const US_MW_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KMDW',
    name: 'Chicago Midway',
    region: 'US-MW',
    hubTier: 'regional',
    lat: 41.7868,
    lon: -87.7522,
    produce: { general: 1.35, supplies: 1.2, electronics: 1.0 },
    consume: { perishables: 1.05, machinery: 0.95 },
  },
  {
    icao: 'KCMH',
    name: 'Columbus/John Glenn',
    region: 'US-MW',
    hubTier: 'regional',
    lat: 39.998,
    lon: -82.8919,
    ...dryRegional,
  },
  {
    icao: 'KTOL',
    name: 'Toledo Express',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.5868,
    lon: -83.8078,
    ...drySpoke,
  },
  {
    icao: 'KFWA',
    name: 'Fort Wayne International',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.9785,
    lon: -85.1951,
    ...drySpoke,
  },
  {
    icao: 'KCAK',
    name: 'Akron-Canton',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.9162,
    lon: -81.4423,
    ...drySpoke,
  },
  {
    icao: 'KAZO',
    name: 'Kalamazoo/Battle Creek',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.2344,
    lon: -85.5516,
    ...drySpoke,
  },
  {
    icao: 'KLAN',
    name: 'Lansing Capital Region',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.7787,
    lon: -84.5874,
    ...drySpoke,
  },
  {
    icao: 'KGRB',
    name: 'Green Bay/Austin Straubel',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 44.4846,
    lon: -88.1296,
    ...drySpoke,
  },
  {
    icao: 'KATW',
    name: 'Appleton/Outagamie',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 44.2581,
    lon: -88.5191,
    ...drySpoke,
  },
  {
    icao: 'KRST',
    name: 'Rochester MN',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 43.9083,
    lon: -92.5,
    ...drySpoke,
  },
  {
    icao: 'KMLI',
    name: 'Quad Cities/Moline',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 41.4485,
    lon: -90.5075,
    ...drySpoke,
  },
  {
    icao: 'KPIA',
    name: 'Peoria International',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.6642,
    lon: -89.6933,
    ...drySpoke,
  },
  {
    icao: 'KCMI',
    name: 'Champaign/Willard',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.0392,
    lon: -88.2761,
    ...drySpoke,
  },
  {
    icao: 'KRFD',
    name: 'Chicago/Rockford',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 42.1954,
    lon: -89.0972,
    produce: { general: 1.2, supplies: 1.15, machinery: 1.0 },
    consume: { electronics: 0.9, perishables: 0.9 },
  },
  {
    icao: 'KSGF',
    name: 'Springfield-Branson National',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 37.2457,
    lon: -93.3886,
    ...drySpoke,
  },
  {
    icao: 'KEVV',
    name: 'Evansville Regional',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 38.038,
    lon: -87.5306,
    ...drySpoke,
  },
  {
    icao: 'KLAF',
    name: 'Lafayette Purdue University',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 40.4123,
    lon: -86.9369,
    ...drySpoke,
  },
  {
    icao: 'KGFK',
    name: 'Grand Forks International',
    region: 'US-MW',
    hubTier: 'spoke',
    lat: 47.9493,
    lon: -97.1761,
    ...drySpoke,
  },
];

/** US-SC densify (+18). */
export const US_SC_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KDAL',
    name: 'Dallas Love Field',
    region: 'US-SC',
    hubTier: 'regional',
    lat: 32.8471,
    lon: -96.8518,
    produce: { general: 1.3, electronics: 1.1, supplies: 1.05 },
    consume: { perishables: 1.0, machinery: 0.95 },
  },
  {
    icao: 'KHOU',
    name: 'Houston Hobby',
    region: 'US-SC',
    hubTier: 'regional',
    lat: 29.6454,
    lon: -95.2789,
    produce: { general: 1.25, machinery: 1.1, supplies: 1.05 },
    consume: { electronics: 0.95, perishables: 0.95 },
  },
  {
    icao: 'KJAN',
    name: 'Jackson-Medgar Wiley Evers',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.3112,
    lon: -90.0759,
    ...drySpoke,
  },
  {
    icao: 'KLCH',
    name: 'Lake Charles Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 30.1261,
    lon: -93.2234,
    ...drySpoke,
  },
  {
    icao: 'KGPT',
    name: 'Gulfport-Biloxi',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 30.4073,
    lon: -89.07,
    ...drySpoke,
  },
  {
    icao: 'KMOB',
    name: 'Mobile Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 30.6912,
    lon: -88.2428,
    ...drySpoke,
  },
  {
    icao: 'KBPT',
    name: 'Beaumont/Jack Brooks',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 29.9508,
    lon: -94.0207,
    ...drySpoke,
  },
  {
    icao: 'KMAF',
    name: 'Midland International',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 31.9425,
    lon: -102.202,
    produce: { machinery: 1.2, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, perishables: 0.85 },
  },
  {
    icao: 'KLBB',
    name: 'Lubbock Preston Smith',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.6636,
    lon: -101.821,
    ...drySpoke,
  },
  {
    icao: 'KACT',
    name: 'Waco Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 31.6113,
    lon: -97.2305,
    ...drySpoke,
  },
  {
    icao: 'KTYR',
    name: 'Tyler Pounds Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.3541,
    lon: -95.4024,
    ...drySpoke,
  },
  {
    icao: 'KGGG',
    name: 'Longview/East Texas Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.384,
    lon: -94.7115,
    ...drySpoke,
  },
  {
    icao: 'KTXK',
    name: 'Texarkana Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.4537,
    lon: -93.991,
    ...drySpoke,
  },
  {
    icao: 'KXNA',
    name: 'Northwest Arkansas National',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 36.2819,
    lon: -94.3068,
    produce: { general: 1.2, electronics: 1.05, supplies: 1.0 },
    consume: { perishables: 0.95, machinery: 0.9 },
  },
  {
    icao: 'KMLU',
    name: 'Monroe Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 32.5109,
    lon: -92.0377,
    ...drySpoke,
  },
  {
    icao: 'KSPS',
    name: 'Wichita Falls/Sheppard AFB',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 33.9888,
    lon: -98.4919,
    ...drySpoke,
  },
  {
    icao: 'KGRK',
    name: 'Killeen-Fort Cavazos Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 31.0672,
    lon: -97.8289,
    ...drySpoke,
  },
  {
    icao: 'KSJT',
    name: 'San Angelo Regional',
    region: 'US-SC',
    hubTier: 'spoke',
    lat: 31.3577,
    lon: -100.496,
    ...drySpoke,
  },
];

/** US-SE densify (+18). */
export const US_SE_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KPBI',
    name: 'Palm Beach International',
    region: 'US-SE',
    hubTier: 'regional',
    lat: 26.6832,
    lon: -80.0956,
    produce: { perishables: 1.2, general: 1.15, supplies: 1.0 },
    consume: { electronics: 0.95, machinery: 0.85 },
  },
  {
    icao: 'KSFB',
    name: 'Orlando Sanford',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 28.7776,
    lon: -81.2375,
    ...drySpoke,
  },
  {
    icao: 'KTLH',
    name: 'Tallahassee International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 30.3965,
    lon: -84.3503,
    ...drySpoke,
  },
  {
    icao: 'KPNS',
    name: 'Pensacola International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 30.4734,
    lon: -87.1866,
    ...drySpoke,
  },
  {
    icao: 'KVPS',
    name: 'Destin-Fort Walton Beach',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 30.4832,
    lon: -86.5254,
    ...drySpoke,
  },
  {
    icao: 'KEYW',
    name: 'Key West International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 24.5561,
    lon: -81.7596,
    produce: { perishables: 1.15, general: 1.0, supplies: 0.95 },
    consume: { electronics: 0.9, machinery: 0.8 },
  },
  {
    icao: 'KSRQ',
    name: 'Sarasota-Bradenton',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 27.3954,
    lon: -82.5544,
    ...drySpoke,
  },
  {
    icao: 'KPIE',
    name: 'St. Pete-Clearwater',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 27.9102,
    lon: -82.6874,
    ...drySpoke,
  },
  {
    icao: 'KDAB',
    name: 'Daytona Beach International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 29.1799,
    lon: -81.0581,
    ...drySpoke,
  },
  {
    icao: 'KGNV',
    name: 'Gainesville Regional',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 29.6901,
    lon: -82.2718,
    ...drySpoke,
  },
  {
    icao: 'KGSO',
    name: 'Piedmont Triad/Greensboro',
    region: 'US-SE',
    hubTier: 'regional',
    lat: 36.0978,
    lon: -79.9373,
    ...dryRegional,
  },
  {
    icao: 'KFAY',
    name: 'Fayetteville Regional',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 34.9912,
    lon: -78.8803,
    ...drySpoke,
  },
  {
    icao: 'KILM',
    name: 'Wilmington International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 34.2706,
    lon: -77.9026,
    ...drySpoke,
  },
  {
    icao: 'KMYR',
    name: 'Myrtle Beach International',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 33.6797,
    lon: -78.9283,
    ...drySpoke,
  },
  {
    icao: 'KCAE',
    name: 'Columbia Metropolitan',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 33.9388,
    lon: -81.1195,
    ...drySpoke,
  },
  {
    icao: 'KAGS',
    name: 'Augusta Regional',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 33.3699,
    lon: -81.9645,
    ...drySpoke,
  },
  {
    icao: 'KCHA',
    name: 'Chattanooga Metropolitan',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 35.0353,
    lon: -85.2038,
    ...drySpoke,
  },
  {
    icao: 'KTRI',
    name: 'Tri-Cities TN/VA',
    region: 'US-SE',
    hubTier: 'spoke',
    lat: 36.4752,
    lon: -82.4074,
    ...drySpoke,
  },
];

/** US-NE densify (+18). */
export const US_NE_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KROC',
    name: 'Rochester NY/Greater Rochester',
    region: 'US-NE',
    hubTier: 'regional',
    lat: 43.1189,
    lon: -77.6724,
    ...dryRegional,
  },
  {
    icao: 'KSYR',
    name: 'Syracuse Hancock',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 43.1112,
    lon: -76.1063,
    ...drySpoke,
  },
  {
    icao: 'KMHT',
    name: 'Manchester-Boston Regional',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 42.9326,
    lon: -71.4357,
    ...drySpoke,
  },
  {
    icao: 'KBGR',
    name: 'Bangor International',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.8074,
    lon: -68.8281,
    ...drySpoke,
  },
  {
    icao: 'KBTV',
    name: 'Burlington International',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 44.4719,
    lon: -73.1533,
    ...drySpoke,
  },
  {
    icao: 'KACY',
    name: 'Atlantic City International',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 39.4576,
    lon: -74.5772,
    ...drySpoke,
  },
  {
    icao: 'KMDT',
    name: 'Harrisburg International',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.1935,
    lon: -76.7634,
    ...drySpoke,
  },
  {
    icao: 'KABE',
    name: 'Lehigh Valley/Allentown',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.6521,
    lon: -75.4404,
    ...drySpoke,
  },
  {
    icao: 'KAVP',
    name: 'Wilkes-Barre/Scranton',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.3385,
    lon: -75.7234,
    ...drySpoke,
  },
  {
    icao: 'KERI',
    name: 'Erie International',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 42.082,
    lon: -80.1762,
    ...drySpoke,
  },
  {
    icao: 'KCRW',
    name: 'Charleston WV/Yeager',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.3731,
    lon: -81.5932,
    ...drySpoke,
  },
  {
    icao: 'KHTS',
    name: 'Huntington Tri-State',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.3667,
    lon: -82.558,
    ...drySpoke,
  },
  {
    icao: 'KROA',
    name: 'Roanoke-Blacksburg',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 37.3255,
    lon: -79.9754,
    ...drySpoke,
  },
  {
    icao: 'KCHO',
    name: 'Charlottesville-Albemarle',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 38.1386,
    lon: -78.4529,
    ...drySpoke,
  },
  {
    icao: 'KSWF',
    name: 'New York Stewart',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.5041,
    lon: -74.1048,
    produce: { general: 1.2, supplies: 1.1, electronics: 0.95 },
    consume: { perishables: 0.95, machinery: 0.9 },
  },
  {
    icao: 'KHPN',
    name: 'Westchester County',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 41.067,
    lon: -73.7076,
    ...drySpoke,
  },
  {
    icao: 'KISP',
    name: 'Long Island MacArthur',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 40.7952,
    lon: -73.1002,
    ...drySpoke,
  },
  {
    icao: 'KBGM',
    name: 'Greater Binghamton',
    region: 'US-NE',
    hubTier: 'spoke',
    lat: 42.2087,
    lon: -75.9798,
    ...drySpoke,
  },
];

/** US-W densify (+20). CA/PNW commercial only. */
export const US_W_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KSBA',
    name: 'Santa Barbara Municipal',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 34.4262,
    lon: -119.841,
    ...drySpoke,
  },
  {
    icao: 'KBFL',
    name: 'Bakersfield Meadows Field',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 35.4336,
    lon: -119.057,
    produce: { perishables: 1.25, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KPSP',
    name: 'Palm Springs International',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 33.8297,
    lon: -116.507,
    ...drySpoke,
  },
  {
    icao: 'KMRY',
    name: 'Monterey Regional',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 36.587,
    lon: -121.843,
    ...drySpoke,
  },
  {
    icao: 'KSBP',
    name: 'San Luis Obispo County',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 35.2368,
    lon: -120.642,
    ...drySpoke,
  },
  {
    icao: 'KSMX',
    name: 'Santa Maria Public',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 34.8989,
    lon: -120.457,
    ...drySpoke,
  },
  {
    icao: 'KSTS',
    name: 'Charles M. Schulz/Sonoma County',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 38.5089,
    lon: -122.813,
    ...drySpoke,
  },
  {
    icao: 'KSCK',
    name: 'Stockton Metropolitan',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.8942,
    lon: -121.238,
    produce: { perishables: 1.3, general: 1.15, supplies: 1.05 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KMOD',
    name: 'Modesto City-County',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 37.6256,
    lon: -120.954,
    produce: { perishables: 1.25, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KRDD',
    name: 'Redding Municipal',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.509,
    lon: -122.293,
    ...drySpoke,
  },
  {
    icao: 'KACV',
    name: 'California Redwood Coast/Arcata',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 40.9781,
    lon: -124.109,
    ...drySpoke,
  },
  {
    icao: 'KPAE',
    name: 'Seattle Paine Field',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 47.9063,
    lon: -122.282,
    produce: { machinery: 1.25, electronics: 1.15, general: 1.1 },
    consume: { perishables: 0.95, supplies: 0.95 },
  },
  {
    icao: 'KPSC',
    name: 'Tri-Cities WA/Pasco',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.2647,
    lon: -119.119,
    produce: { perishables: 1.2, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KYKM',
    name: 'Yakima Air Terminal',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.5682,
    lon: -120.544,
    produce: { perishables: 1.3, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KSLE',
    name: 'Salem McNary Field',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 44.9095,
    lon: -123.003,
    ...drySpoke,
  },
  {
    icao: 'KALW',
    name: 'Walla Walla Regional',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.0949,
    lon: -118.289,
    produce: { perishables: 1.25, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KLWS',
    name: 'Lewiston-Nez Perce County',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.3745,
    lon: -117.015,
    ...drySpoke,
  },
  {
    icao: 'KPUW',
    name: 'Pullman-Moscow Regional',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 46.7439,
    lon: -117.11,
    ...drySpoke,
  },
  {
    icao: 'KEAT',
    name: 'Wenatchee Pangborn',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 47.398,
    lon: -120.207,
    produce: { perishables: 1.35, general: 1.1, supplies: 1.0 },
    consume: { electronics: 0.85, machinery: 0.85 },
  },
  {
    icao: 'KOTH',
    name: 'North Bend/Southwest Oregon',
    region: 'US-W',
    hubTier: 'spoke',
    lat: 43.4171,
    lon: -124.246,
    ...drySpoke,
  },
];

/** US-MT densify (+16). Rockies / SW. */
export const US_MT_DENSIFY_HUBS: readonly DensifyHub[] = [
  {
    icao: 'KGTF',
    name: 'Great Falls International',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 47.482,
    lon: -111.371,
    ...drySpoke,
  },
  {
    icao: 'KGPI',
    name: 'Kalispell/Glacier Park',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 48.3105,
    lon: -114.256,
    ...drySpoke,
  },
  {
    icao: 'KBTM',
    name: 'Butte Bert Mooney',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 45.9548,
    lon: -112.497,
    ...drySpoke,
  },
  {
    icao: 'KCYS',
    name: 'Cheyenne Regional',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 41.1557,
    lon: -104.812,
    ...drySpoke,
  },
  {
    icao: 'KPUB',
    name: 'Pueblo Memorial',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 38.2891,
    lon: -104.497,
    ...drySpoke,
  },
  {
    icao: 'KEGE',
    name: 'Eagle County Regional',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 39.6426,
    lon: -106.918,
    ...drySpoke,
  },
  {
    icao: 'KASE',
    name: 'Aspen-Pitkin County',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 39.2232,
    lon: -106.869,
    ...drySpoke,
  },
  {
    icao: 'KSAF',
    name: 'Santa Fe Municipal',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 35.6171,
    lon: -106.089,
    ...drySpoke,
  },
  {
    icao: 'KROW',
    name: 'Roswell Air Center',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 33.3016,
    lon: -104.531,
    ...drySpoke,
  },
  {
    icao: 'KFLG',
    name: 'Flagstaff Pulliam',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 35.1385,
    lon: -111.671,
    ...drySpoke,
  },
  {
    icao: 'KPRC',
    name: 'Prescott Love Field',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 34.6541,
    lon: -112.42,
    ...drySpoke,
  },
  {
    icao: 'KPIH',
    name: 'Pocatello Regional',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 42.9098,
    lon: -112.596,
    ...drySpoke,
  },
  {
    icao: 'KTWF',
    name: 'Twin Falls Magic Valley',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 42.4818,
    lon: -114.488,
    ...drySpoke,
  },
  {
    icao: 'KCDC',
    name: 'Cedar City Regional',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 37.701,
    lon: -113.099,
    ...drySpoke,
  },
  {
    icao: 'KSGU',
    name: 'St. George Regional',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 37.0364,
    lon: -113.51,
    ...drySpoke,
  },
  {
    icao: 'KRKS',
    name: 'Rock Springs-Sweetwater',
    region: 'US-MT',
    hubTier: 'spoke',
    lat: 41.5942,
    lon: -109.065,
    ...drySpoke,
  },
];

export const US_DENSIFY_HUB_COUNT =
  US_MW_DENSIFY_HUBS.length +
  US_SC_DENSIFY_HUBS.length +
  US_SE_DENSIFY_HUBS.length +
  US_NE_DENSIFY_HUBS.length +
  US_W_DENSIFY_HUBS.length +
  US_MT_DENSIFY_HUBS.length;
