/**
 * Mexico densify — commercial MM* airports (MSFS + SimBrief).
 * Merged into MX_CAREER_HUBS. No bush strips.
 */
import type { CommodityId, HubTier } from './types/career-economy.js';
import type { MxCareerRegion } from './career-mx-hubs.js';

type MxDensifyHub = {
  icao: string;
  name: string;
  region: MxCareerRegion;
  hubTier: HubTier;
  lat: number;
  lon: number;
  produce: Partial<Record<CommodityId, number>>;
  consume: Partial<Record<CommodityId, number>>;
};

const drySpoke = {
  produce: { general: 1.1, supplies: 1.0, perishables: 1.05 },
  consume: { electronics: 0.9, machinery: 0.85 },
} as const;

const city = {
  produce: { general: 1.2, electronics: 1.1, supplies: 1.0 },
  consume: { perishables: 1.1, machinery: 0.9 },
} as const;

const agroSpoke = {
  produce: { perishables: 1.35, general: 1.0, supplies: 0.95 },
  consume: { electronics: 0.85, machinery: 0.85, general: 0.9 },
} as const;

const petroSpoke = {
  produce: { machinery: 1.25, general: 1.05, supplies: 1.0 },
  consume: { electronics: 0.85, perishables: 0.85 },
} as const;

/** MX densify (+37) → 83 total. MMDM dropped — absent in stock MSFS. */
export const MX_DENSIFY_HUBS: readonly MxDensifyHub[] = [
  {
    icao: 'MMMZ',
    name: 'Mazatlan',
    region: 'MX-N',
    hubTier: 'regional',
    lat: 23.1614,
    lon: -106.2661,
    ...city,
  },
  {
    icao: 'MMSM',
    name: 'Felipe Angeles AIFA',
    region: 'MX-C',
    hubTier: 'regional',
    lat: 19.7553,
    lon: -99.0164,
    ...city,
  },
  {
    icao: 'MMAN',
    name: 'Del Norte Monterrey',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 25.8656,
    lon: -100.2372,
    ...drySpoke,
  },
  {
    icao: 'MMBT',
    name: 'Bahias de Huatulco',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 15.7753,
    lon: -96.2625,
    ...drySpoke,
  },
  {
    icao: 'MMPS',
    name: 'Puerto Escondido',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 15.8769,
    lon: -97.0892,
    ...drySpoke,
  },
  {
    icao: 'MMCN',
    name: 'Ciudad Obregon',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 27.3926,
    lon: -109.8331,
    ...drySpoke,
  },
  {
    icao: 'MMGM',
    name: 'Guaymas',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 27.9689,
    lon: -110.925,
    ...drySpoke,
  },
  {
    icao: 'MMPE',
    name: 'Puerto Penasco',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 31.3519,
    lon: -113.3056,
    ...drySpoke,
  },
  {
    icao: 'MMPN',
    name: 'Uruapan',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 19.3967,
    lon: -102.0392,
    ...drySpoke,
  },
  {
    icao: 'MMCB',
    name: 'Cuernavaca',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 18.8348,
    lon: -99.2614,
    ...drySpoke,
  },
  {
    icao: 'MMCV',
    name: 'Ciudad Victoria',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 23.7033,
    lon: -98.9564,
    ...drySpoke,
  },
  {
    icao: 'MMMV',
    name: 'Monclova',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 26.9557,
    lon: -101.47,
    ...drySpoke,
  },
  {
    icao: 'MMNG',
    name: 'Nogales',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 31.2261,
    lon: -110.9758,
    ...drySpoke,
  },
  {
    icao: 'MMJA',
    name: 'Xalapa',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 19.475,
    lon: -96.7975,
    ...drySpoke,
  },
  {
    icao: 'MMSF',
    name: 'San Felipe',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 30.9302,
    lon: -114.8089,
    ...drySpoke,
  },
  {
    icao: 'MMIT',
    name: 'Ixtepec',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 16.4493,
    lon: -95.0937,
    ...drySpoke,
  },
  {
    icao: 'MMCC',
    name: 'Ciudad Acuna',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 29.3339,
    lon: -101.1008,
    ...drySpoke,
  },
  {
    icao: 'MMLT',
    name: 'Loreto',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 25.9892,
    lon: -111.3481,
    ...drySpoke,
  },
  {
    icao: 'MMPG',
    name: 'Piedras Negras',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 28.6275,
    lon: -100.535,
    ...drySpoke,
  },
  {
    icao: 'MMDA',
    name: 'Ciudad Constitucion',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 25.0538,
    lon: -111.615,
    ...drySpoke,
  },
  {
    icao: 'MMES',
    name: 'Ensenada',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 31.7953,
    lon: -116.6025,
    ...drySpoke,
  },
  {
    icao: 'MMJC',
    name: 'Atizapan',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 19.5733,
    lon: -99.2881,
    ...drySpoke,
  },
  {
    icao: 'MMSL',
    name: 'Cabo San Lucas',
    region: 'MX-Y',
    hubTier: 'spoke',
    lat: 22.8908,
    lon: -109.9208,
    ...drySpoke,
  },
  {
    icao: 'MMTA',
    name: 'Tlaxcala',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 19.3372,
    lon: -98.1733,
    ...drySpoke,
  },
  {
    icao: 'MMPA',
    name: 'Poza Rica El Tajin',
    region: 'MX-S',
    hubTier: 'regional',
    lat: 20.6027,
    lon: -97.4608,
    ...petroSpoke,
  },
  {
    icao: 'MMCY',
    name: 'Celaya',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 20.546,
    lon: -100.8865,
    ...agroSpoke,
  },
  {
    icao: 'MMLC',
    name: 'Lazaro Cardenas',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 18.0017,
    lon: -102.2203,
    ...petroSpoke,
  },
  {
    icao: 'MMPQ',
    name: 'Palenque',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 17.5332,
    lon: -92.0155,
    ...agroSpoke,
  },
  {
    icao: 'MMGR',
    name: 'Guerrero Negro',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 28.0261,
    lon: -114.024,
    ...drySpoke,
  },
  {
    icao: 'MMTN',
    name: 'Tamuin',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 22.0383,
    lon: -98.8065,
    ...agroSpoke,
  },
  {
    icao: 'MMCH',
    name: 'Chilpancingo',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 17.5741,
    lon: -99.5154,
    ...drySpoke,
  },
  {
    icao: 'MMCA',
    name: 'Cananea',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 31.0662,
    lon: -110.0979,
    ...drySpoke,
  },
  {
    icao: 'MMZM',
    name: 'Zamora',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 20.045,
    lon: -102.276,
    ...agroSpoke,
  },
  {
    icao: 'MMCO',
    name: 'Comitan',
    region: 'MX-S',
    hubTier: 'spoke',
    lat: 16.1767,
    lon: -92.0506,
    ...agroSpoke,
  },
  {
    icao: 'MMPC',
    name: 'Pachuca',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 20.0774,
    lon: -98.7825,
    ...drySpoke,
  },
  {
    icao: 'MMMG',
    name: 'Mulege',
    region: 'MX-N',
    hubTier: 'spoke',
    lat: 26.9053,
    lon: -111.9707,
    ...drySpoke,
  },
  {
    icao: 'MMTX',
    name: 'Tuxpan Jalisco',
    region: 'MX-C',
    hubTier: 'spoke',
    lat: 19.5996,
    lon: -103.371,
    ...agroSpoke,
  },
];

export const MX_DENSIFY_HUB_COUNT = MX_DENSIFY_HUBS.length;
